export default {
  // General
  SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
  SET_SPINNER_STATUS: 'SET_SPINNER_STATUS',
  SET_LOADER: 'SET_LOADER',
  SET_TABLE_LOADER: 'SET_TABLE_LOADER',
  SET_ERROR_POPUP: 'SET_ERROR_POPUP',
  SET_ORG_TYPES: 'SET_ORG_TYPES',

}
